baseURL = 'https://embeddingbits.github.io/'
languageCode = 'en-us'
title = "eBits's Base Address"
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Thoughts and Expressions"

# Appearance settings
theme = 'dark'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = "Hi, I'm eBits"
homeIntroContent = """
Hi, I’m Amiitesh, an open-source enthusiast and passionate Linux and Neovim user. I love working at the intersection of Embedded Systems, Hardware Optimisation, and Low-Level Programming and VLSI.

I contribute to projects across Embedded Systems, Computer Networks, and Systems Programming, and I’m currently diving deeper into Wayland and VLSI design. I enjoy crafting command-line tools and experimenting with C, Zig, C++, Golang and Verilog.

Outside tech, I’m a classical pianist and a diehard fan of Chopin's repertoire.

---
"""

language = 'en'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'
showFooter = true
footerContent = """
Copyright © 2025 Amiitesh TSP.
"""

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/amiitesh-pradeep-kumar-582bb831a/"

[[params.social]]
name = "github"
url = "https://github.com/embeddingbits"

[[params.social]]
name = "instagram"
url = "https://instagram.com/tspamiitesh"

# Main menu pages
[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "projects"
url = "/projects"

[[params.menu]]
name = "my_software"
url = "/software"

[[params.menu]]
name = "tags"
url = "/tags"

[[params.menu]]
name = "contact"
url = "/contact"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'gruvbox'
